server:
    port: 8080
spring:
    application:
        name: call-center
    h2:
        console:
            enabled: true
            path: /h2
    datasource:
        url: jdbc:h2:mem:example-service
        username: sa
        password: password
        driverClassName: org.h2.Driver
