grpc:
  server:
    port: 50056

spring:
  application:
    name: Call Center Service
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2
    datasource:
      url: jdbc:h2:mem:callcenter-db
      username: sa
      password: password
      driverClassName: org.h2.Driver